"""Markdown engineering report generator.

Renders the full pipeline state into a human-readable report. Structure:
summary -> requirements & assumptions -> architecture -> CAD -> checks ->
risks -> BOM -> limitations -> next steps. Honesty rules: assumptions and
limitations are always included, never buried.
"""

from app.schemas import EngineeringReportState


def _table(headers: list[str], rows: list[list[str]]) -> str:
    out = "| " + " | ".join(headers) + " |\n"
    out += "|" + "|".join("---" for _ in headers) + "|\n"
    for r in rows:
        out += "| " + " | ".join(str(c) for c in r) + " |\n"
    return out


def render_report(state: EngineeringReportState) -> str:
    req, arch, cad = state.requirements, state.architecture, state.cad_params
    sim, risk, bom = state.simulation, state.risk_report, state.bom
    assert req and arch and cad and sim and risk and bom, "report requires full pipeline state"

    md: list[str] = []
    md.append(f"# Engineering Report — {state.design_id}\n")
    md.append(f"**Prompt:** {state.prompt}\n")
    md.append("> **This is a concept-level engineering package generated by an AI "
              "assistant.** It is not a certified design. All calculations are "
              "first-order estimates and must be reviewed by a qualified engineer "
              "before fabrication or deployment.\n")

    # Summary
    passed = sum(1 for c in sim.checks if c.passed)
    md.append("## Summary\n")
    md.append(f"- Design: 4-wheel skid-steer mobile inspection robot\n"
              f"- Estimated total mass: **{sim.total_mass_kg} kg** "
              f"({sim.loaded_mass_kg} kg with payload)\n"
              f"- Estimated runtime: **{sim.estimated_runtime_hr} h** "
              f"(required {req.runtime_hr} h, margin {sim.runtime_margin}x)\n"
              f"- Estimated cost: **${bom.total_cost_usd:.2f}** "
              f"(budget ${req.max_cost_usd:.0f})\n"
              f"- Engineering checks: **{passed}/{len(sim.checks)} passed**\n")

    # Requirements
    md.append("## Requirements\n")
    md.append(_table(
        ["Field", "Value"],
        [["Payload", f"{req.payload_kg} kg"],
         ["Runtime", f"{req.runtime_hr} h"],
         ["Max dimensions", " x ".join(f"{d:.0f}" for d in req.max_dimensions_mm) + " mm"],
         ["Environment", req.environment.value],
         ["Max cost", f"${req.max_cost_usd:.0f}"],
         ["Locomotion", req.locomotion_type.value],
         ["Sensors", ", ".join(req.sensors_required)],
         ["Max speed", f"{req.max_speed_m_s} m/s"],
         ["Max ramp", f"{req.max_ramp_deg} deg"]]))

    md.append("### Assumptions\n")
    md.append(_table(
        ["Field", "Assumed value", "Rationale", "Confidence"],
        [[a.field, a.assumed_value, a.rationale, a.confidence] for a in req.assumptions]))
    if req.unknowns:
        md.append("### Open questions for the customer\n")
        md.extend(f"- {u}\n" for u in req.unknowns)

    # Architecture
    md.append("\n## System Architecture\n")
    md.append(f"- **Drivetrain:** {arch.drivetrain}\n"
              f"- **Chassis:** {arch.chassis_topology} — {arch.chassis_material}\n"
              f"- **Motors:** {arch.motor.count}x {arch.motor.motor_class} "
              f"({arch.motor.rated_torque_nm} Nm rated)\n"
              f"- **Battery:** {arch.battery.chemistry}, "
              f"{arch.battery.nominal_voltage_v} V / {arch.battery.capacity_wh:.0f} Wh\n")
    md.append("### Design rationale\n")
    md.extend(f"- {r}\n" for r in arch.rationale)
    md.append("### Sensor placement\n")
    md.append(_table(["Sensor", "Location"], [[k, v] for k, v in arch.sensor_placement.items()]))

    # CAD
    md.append("\n## CAD\n")
    md.append(f"Template `{cad.template}` — chassis {cad.chassis_length_mm:.0f} x "
              f"{cad.chassis_width_mm:.0f} x {cad.chassis_thickness_mm:.0f} mm, "
              f"wheelbase {cad.wheelbase_mm:.0f} mm, track {cad.track_width_mm:.0f} mm, "
              f"mast {cad.mast_height_mm:.0f} mm.\n")
    if state.cad_export_note:
        md.append(f"\n*CAD export note: {state.cad_export_note}*\n")

    # Checks
    md.append("\n## Engineering Checks\n")
    md.append(_table(
        ["Check", "Value", "Threshold", "Result", "Formula"],
        [[c.name, f"{c.value} {c.unit}", str(c.threshold),
          "PASS" if c.passed else "**FAIL**", f"`{c.formula}`"] for c in sim.checks]))
    md.append(f"\nCenter of gravity height ~{sim.cog_height_mm} mm; static tip angles "
              f"{sim.tip_angle_lateral_deg} deg (lateral) / "
              f"{sim.tip_angle_longitudinal_deg} deg (longitudinal). "
              f"Chassis bending stress {sim.chassis_bending_stress_mpa} MPa "
              f"(SF {sim.chassis_safety_factor}).\n")

    # Risks
    md.append("\n## Risk Report\n")
    md.append(f"**Overall:** {risk.overall_assessment}\n\n")
    md.append(_table(
        ["ID", "Severity", "Risk", "Mitigation"],
        [[i.id, i.severity.value.upper(), f"**{i.title}** — {i.description}", i.mitigation]
         for i in risk.items]))

    # BOM
    md.append("\n## Bill of Materials\n")
    md.append(_table(
        ["Part #", "Name", "Qty", "Unit $", "Total $"],
        [[i.part_number, i.name, str(i.quantity),
          f"{i.unit_cost_usd:.2f}", f"{i.total_cost_usd:.2f}"] for i in bom.items]))
    md.append(f"\n**Total: ${bom.total_cost_usd:.2f}** — {bom.pricing_disclaimer}\n")

    # Limitations
    md.append("\n## Limitations\n")
    md.extend(f"- {lim}\n" for lim in sim.limitations)

    md.append("\n## Next Steps\n")
    md.append("1. Resolve the open questions above with the customer.\n"
              "2. Detailed CAD pass: motor mounts, cable routing, bumpers, covers.\n"
              "3. FEA on chassis and mast; thermal check on electronics bay.\n"
              "4. Prototype build and endurance test against the runtime requirement.\n")

    return "".join(md)
